export const ADD_RECORDS = 'ADD_RECORDS';
export const RECORDS_LOADING = 'RECORDS_LOADING';
export const RECORDS_FAILED = 'RECORDS_FAILED';

export const ADD_PROJECTS = 'ADD_PROJECTS';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';

