export const ADD_FILES = 'ADD_FILES';
export const FILES_LOADING = 'FILES_LOADING';
export const FILES_FAILED = 'FILES_FAILED';

export const ADD_PROJECTS = 'ADD_PROJECTS';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';

